-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 19:00:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escola_Musica_para_todos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escola_Musica_para_todos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escola_Musica_para_todos` DEFAULT CHARACTER SET utf8 ;
USE `Escola_Musica_para_todos` ;

-- -----------------------------------------------------
-- Table `Escola_Musica_para_todos`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Musica_para_todos`.`Aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `idade` INT NOT NULL,
  `Email` VARCHAR(80) NOT NULL,
  `telefone` CHAR(12) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica_para_todos`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Musica_para_todos`.`Professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `idade` INT NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefone` CHAR(12) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica_para_todos`.`Aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Musica_para_todos`.`Aulas` (
  `id_aula` INT NOT NULL AUTO_INCREMENT,
  `data_aula` DATE NOT NULL,
  `instrumento_aula` VARCHAR(80) NOT NULL,
  `horario_aula` datetime NULL,
  `notas_aluno` REAL NULL,
  `frequencia_aulas` FLOAT NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica_para_todos`.`Aluno_aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Musica_para_todos`.`Aluno_aulas` (
  `Aluno_id` INT NOT NULL,
  `Aulas_id` INT NOT NULL,
  INDEX `fk_Aluno_aulas_Aluno1_idx` (`Aluno_id` ASC) VISIBLE,
  INDEX `fk_Aluno_aulas_Aulas1_idx` (`Aulas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_aulas_Aluno1`
    FOREIGN KEY (`Aluno_id`)
    REFERENCES `Escola_Musica_para_todos`.`Aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_aulas_Aulas1`
    FOREIGN KEY (`Aulas_id`)
    REFERENCES `Escola_Musica_para_todos`.`Aulas` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica_para_todos`.`Professor_aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Musica_para_todos`.`Professor_aulas` (
  `Aulas_id` INT NOT NULL,
  `Professor_id` INT NOT NULL,
  INDEX `fk_Professor_aulas_Aulas1_idx` (`Aulas_id` ASC) VISIBLE,
  INDEX `fk_Professor_aulas_Professor1_idx` (`Professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_aulas_Aulas1`
    FOREIGN KEY (`Aulas_id`)
    REFERENCES `Escola_Musica_para_todos`.`Aulas` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_aulas_Professor1`
    FOREIGN KEY (`Professor_id`)
    REFERENCES `Escola_Musica_para_todos`.`Professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
